name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: GOOS=linux GOARCH=arm64 go build -o bin/bootstrap ./cmd/commander/main.go

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985688283435:role/github-actions-nhi-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/
        env:
          TF_VAR_slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          TF_VAR_slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}